build: UVaunzip.c
	gcc -o UVaunzip UVaunzip.c -Wall -Werror
debug: UVauzip.c
	gcc -o UVaunzip_debug UVaunzip.c -Wall -Werror -g
	gdb UVaunzip_debug
clean: UVaunzip UVaunzip_debug
	rm UVaunzip UVaunzip_debug
